apiVersion: v1
kind: ServiceAccount
metadata:
  name: decision-engine-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: decision-engine-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: decision-engine-binding
subjects:
  - kind: ServiceAccount
    name: decision-engine-sa
roleRef:
  kind: Role
  name: decision-engine-role
  apiGroup: rbac.authorization.k8s.io
